### ISSUE TITLE
BUG: Splitting plots to a new pane is a pain.

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/atom-language-julia#60]
If you make a plot in Gadfly but then want to split the plot to a new screen, you get the following error. I was able to reproduce it on 3 computers: 2 Windows, 1 Linux.

Uncaught Error: The workspace can only contain one instance of item [object Object]
/usr/share/atom/resources/app.asar/src/item-registry.js:11
Hide Stack Trace
Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/usr/share/atom/resources/app.asar/src/item-registry.js:11:15)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app.asar/src/pane-container.js:374:25)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:353:19
    at /usr/share/atom/resources/app.asar/src/pane-container.js:97:16
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.didAddPane (/usr/share/atom/resources/app.asar/src/pane-container.js:293:27)
    at Pane.module.exports.Pane.setContainer (/usr/share/atom/resources/app.asar/src/pane.js:98:26)
    at PaneAxis.module.exports.PaneAxis.addChild (/usr/share/atom/resources/app.asar/src/pane-axis.js:144:13)
    at PaneAxis.module.exports.PaneAxis.insertChildAfter (/usr/share/atom/resources/app.asar/src/pane-axis.js:216:19)
    at Pane.module.exports.Pane.split (/usr/share/atom/resources/app.asar/src/pane.js:710:23)
    at Pane.module.exports.Pane.splitRight (/usr/share/atom/resources/app.asar/src/pane.js:672:19)
    at atom-tabs.TabBarView.splitTab (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:392:31)
    at Object.addElementCommands.tabs:split-right (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:127:26)
    at atom-tabs.commandsWithPropagationStopped.(anonymous function) (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:78:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/usr/share/atom/resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
The error was thrown from the tabs package. This issue has already been reported.

**Comment by MikeInnes** [comment]
Same goes for the console – presumably we just need to override the default behaviour here somehow, but I'm not sure exactly how that's done.

FWIW, I use [this patch](https://github.com/atom/tabs/pull/252) for layout management and it's a lot more convenient.

**Comment by MikeInnes** [comment]
I just pushed a hacky fix for this.
